rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>[-\w]+)/$',
        views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^add_page/(?P<category_name_slug>[-\w]+)/$',
        views.add_page, name='add_page'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$', views.search,
        name='search'),
    url(r'^goto/$', views.track_url,
        name='goto'),
    url(r'^add_profile/$', views.register_profile,
        name='add_profile'),
    url(r'^profile/$', views.profile,
        name='profile'),
    url(r'^edit_profile/(?P<id>\d+)/$', views.edit_profile,
        name='edit_profile'),
    url(r'^like_category/$', views.like_category,
        name='like_category'),
    url(r'^suggest_category/$', views.suggest_category,
        name='suggest_category'),
    url(r'^auto_add_page/$', views.auto_add_page,
        name='auto_add_page'),
    url(r'^wiki/$', views.wiki_article_index,
        name='wiki_article_index'),
    url(r'^article/(?P<slug>[-\w]+)/$',views.wiki_article_detail,
        name='wiki_article_detail'),
    url(r'^history/(?P<slug>[-\w]+)/$', views.wiki_article_history,
        name='wiki_article_history'),
    url(r'^add/article$', views.wiki_add_article,
        name='wiki_add_article'),
    url(r'^edit/article(?P<slug>[-\w]+)/$', views.wiki_edit_article,
        name='wiki_edit_article'),
    url(r'^image/(?P<width>[0-9]+)x(?P<height>[0-9]+)/$', views.placeholder, 
        name='placeholder'),



)

tango_with_django_project/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page, if
# successful at logging

class MyRegistrationView(RegistrationView):

    def get_success_url(self, request, user):
        return '/rango/add_profile/'


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}),)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    # This line is required.Links UserProfile to a User Model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username


class PublishedArticlesManager(models.Manager):
    """define a custom model manager, which is a queryset that only
    returns the published articles."""

    def get_query_set(self):
        return super(PublishedArticlesManager, self).get_query_set(
            is_published=True)


class Article(models.Model):

    title = models.CharField(max_length=100)
    text = models.TextField(help_text="Formatted using ReST")
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(User)
    is_published = models.BooleanField(default=False, verbose_name="Publish?")
    created_on = models.DateTimeField(auto_now_add=True)
    objects = models.Manager() # default model manager 
    # article = models.Manger()
    published = PublishedArticlesManager()

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('wiki_article_detail', (), {'slug': self.slug})


class Edit(models.Model):

    article = models.ForeignKey(Article)
    editor = models.ForeignKey(User)
    edited_on = models.DateTimeField(auto_now_add=True)
    summary = models.CharField(max_length=100)

    class Meta:
        ordering = ['-edited_on']

    def __unicode__(self):
        return '{0} - {1} - {2}'.format(
            self.summary, self.editor, self.edited_on)

    @models.permalink
    def get_absolute_url(self):
        return ('wiki_edit_detail', self.id)

rango/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from datetime import datetime
from .models import Category, Page, UserProfile, Article, Edit
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm, ArticleForm, EditForm, ImageForm
from .bing_search import requests_query
# def index(request):
# return HttpResponse("Rango says hey there world!")
# construct a dictionary to pass to the template engine as ites context.
# Note the Key blodmessage is the same as {{ blodmessage }} in the template.
#     context_dict = {'boldmessage': 'I am blod font from the context'}

# return a rendered response to send to the client.
# we make use of the shortcut function to make our lives easier.
# Note that the first parameter is the template we wish to use.
#     return render(request, 'rango/index.html', context_dict)
def placeholder(request, width, height):
    form = ImageForm({'height':height, 'width':width})
    if form.is_valid():
        image = form.generate()
        return HttpResponse(image, content_type='image/png')
    else:
        return HttpResponseBadRequest('Invalid Image Request')




def index_with_client_side_cookies(request):
    # Query the database for a list of all categories currently stored.
    # Order the cateogries by no. like in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary which will be passed to
    # the template engine.
    page_list = Page.objects.order_by('-views')[:5]
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {'categories': category_list,
                    'pages': page_list}

    # get the number of visits to the site.
    # we use the COOKIES.get() func to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, we default to zero and cast that.
    visits = int(request.COOKIES.get('visits', '1'))
    reset_last_visit_time = False
    response = render(request, 'rango/index.html', context_dict)
    # Does the cookie last_vist exists?
    if 'last_vist' in request.COOKIES:
        # yes it does, get the cookie's value
        last_vist = request.COOKIES.get('last_vist')
        # cast the value to a python date/time object
        last_vist_time = datetime.strptime(last_vist[:-7], "%Y-%m-%d %H:%M:%S")

        # If it's been more than a day since the last vist...
        if (datetime.now() - last_vist_time).days > 0:
            visits += 1
            # ... and flag that the cookie last visit needs to be updated
            reset_last_visit_time = True
    else:
        # Cookie last_vist doesn't exist, so flag that itshould be set.
        reset_last_visit_time = True
        context_dict['visits'] = visits
        response = render(request, 'rango/index.html', context_dict)

    if reset_last_visit_time:
        response.set_cookie('last_vist', datetime.now())
        response.set_cookie('visits', visits)
    return response


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {'categories': category_list,
                    'pages': page_list}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_vist_time = datetime.strptime(
            last_visit[:-7], "%Y-%m-%d %H:%M:%S")
        if (datetime.now() - last_vist_time).days > 0:
            visits += 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    context_dict['visits'] = visits

    return render(request, 'rango/index.html', context_dict)


def about(request):
    # return HttpResponse("Rango says here is the about page.")
    count = request.session.get('visits')
    if not count:
        count = 0

    return render(request, 'rango/about.html', {'visits': count})


def category(request, category_name_slug):

    context_dict = {}

    try:
        # can we find a category name slug with the given name?
        # if we can't, the .get() method raises a DoesNotExist exception.
        # so the .get() method returns one model instance or raises an
        # exception.
        category = Category.objects.get(slug=category_name_slug)
        category.views += 1
        category.save()
        context_dict['category_name'] = category.name
        context_dict['views'] = category.views
        # retrieve all of the associated pages.
        # note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category).order_by('-views')

        # add our results list ot the template context under name pages
        context_dict['pages'] = pages
        # we also add the category object from the database to the context dic.
        # we'll use this in the template to veryfy that the category exists.
        context_dict['category'] = category

        context_dict['category_name_slug'] = category_name_slug

    except Category.DoesNotExist:
        # we get here if we didn't finde the special category.
        # Don't do anything - the template displays the "no category" message
        # for us.
        pass

    result_list = []
    if request.method == 'POST':
        query = request.POST.get('query', False)
        if query:
            result_list = requests_query(query.strip())
    context_dict['result_list'] = result_list

    return render(request, "rango/category.html", context_dict)


@login_required
def add_category(request):
    if request.method == 'POST':
        # print 'POST:',request.POST
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            # print 'form:',form
            # print cat, cat.slug
            # return index(request)
        else:
            print form.errors
    else:
        form = CategoryForm()
    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form': form,
                    'category': cat,
                    'category_name_slug': category_name_slug, }

    return render(request, 'rango/add_page.html', context_dict)


def register(request):

    # a boolean value for telling the template whether the registration
    # was successful.
    # set to False initially code change value to  True when reigstration
    # succeeds.
    registered = False

    # If it's a Http Post, we're interested in processing form data.
    if request.method == 'POST':
        # attempt ot grad info from the raw form info.
        # note that we make use of both userform userprofileform
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # if the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            # now we hash the password with the set_password method.
            # once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # now sort out the userprofile instance.
            # since we need to set the user attribute ourselves,
            # we set commit=False.
            # this delays saving the model until we're ready to avoid integrity
            # problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        # invalid form or forms mistakes or something else?
        # print problems to the terminal
        # they'll also be shown to the user.
        else:
            print 'user_form errors:', user_form.errors, profile_form.errors

    # not a http post, so we render our form using two modelform instances.
    # these forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):

    # if the request is a HTTP POST, try to pull out the relevant info.
    if request.method == 'POST':
        # gather username and password provided by the user.
        # this info is obtained from the login form.
        username = request.POST.get('username')
        password = request.POST.get('password')

        # use django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if itis.
        user = authenticate(username=username, password=password)

        # if we have a User object, the details are correct.

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %} About {% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
	<script src="{% static 'js/jquery.js'%}"></script>
{% block content %}
	<div class="page-header">
	<h1 class="text-center">About</h1>
	  </div>
	  <div>	
	  	<p>You've been visit {{ visits }} times</p>

		<p></strong></p>
		<img class="img-responsive" src="{% static "images/boss-fight-free-high-quality-stock-images-photos-photography-trees-autumn.jpg" %}" alt="Picture of Rango"/>
	  </div> 

	  <button class="btn btn-default" onclick="alert('You clicked the button using Javascript.')">
	  	Click Me - I run Javascript
	  </button>

	  <button class="btn btn-default"  id='about-btn'>
	  	Click Me - I'm Javascript on Speed</button>	
	  	<p>
	  		This is a example
	  	</p>
	  	<p>
	  		This is another example
	  	</p>
	      

{% endblock %}

templates/rango/add_category.html
{% extends 'base.html' %}

{% block content %}
	<div class="page-header">
	<h1>Add a category</h1>
	</div>

	<form id="category_form" method="post" action="{% url 'add_category' %}">
	{% csrf_token %}
	{% for hidden in form.hidden_fields %}
		{{ hidden }}
	{% endfor %}
	
	{% for field in form.visible_fields %}
		{{ field.errors}}
		{{ field.help_text}}
		{{ field}}
	{% endfor %}
	<input type="submit" name="submit" value="Create Category"/>
	</form>
{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}
{% block content %}

	
	{% if not category_name_slug %}
		<div class="page-header">
		<h1>The specified category does not exist!</h1>
		</div>
	{% else %}
		<div class="page-header">
		<h1>You are adding page in {{ category.name }}</h1>
		</div>
		<form  id="page_form" method="post" action="{% url 'add_page' category_name_slug %}">
		{% csrf_token %}
		{% for hidden in form.hidden_fields %}
		{{ hidden }}
		{% endfor %}

		{% for field in form.visible_fields %}
		{{ field.errors }}<br/>
		{{ field.help_text }}
		{{ field }}
		{% endfor %}
		<br/>
		<input type="submit" name="submit" value="Create Page"/>
		</form>
	{% endif %}

{% endblock %}

templates/rango/category.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title%} {{category_name }} {% endblock %}

{% block content %}
	<div class="page-header">
	<h1>{{ category_name }}</h1>
	</div>

	<p> you've been viewed this category {{ views }} times</p>
	{% if category %}

		<div id='page'>

<!--		{% for page in category.page_set.all %}
			<ul> {{page.title}}</ul>
		{% endfor %}
-->


		{% if pages %}

			<ul>
				{% for page in pages %}
				<li>
					<a href="{% url 'goto' %}?page_id={{page.id}}">{{ page.title }} -- you've been clicked {{page.views}} times</a></li>
				{% endfor %}

			</ul>

		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}
		</div>


		{% if user.is_authenticated %}
		<br/>
		<a href='{% url "add_page" category.slug %}'>add a new page?</a>
		{% endif %}

		<br/>
		<div >
		  <p>
		  <strong id='like_count'>{{ category.likes }}</strong> people like this category

		  {% if user.is_authenticated %}
		  <button id="likes" data-catid="{{ category.id }}" class="btn btn-primary" type="button">
		  <span class='glyphicon glyphicon-thumbs-up'></span>
		  Like?
		  </button>		  
		  {% endif %}
		  </p>

		</div>
		



	{% else %}
		The specified category {{ category_name }} does not exist!
		<a href="{% url 'index' %}">go back?</a>
	{% endif %}

	{% if user.is_authenticated %}
	<div class="row">
		<div class="panel panel-primary">
		  <br/>

		  <form class="form-inline" id="usrer-form" method="post" action="{% url 'category' category.slug %}">{% csrf_token %}
		    <input class="form-control" type="text" size="50" name="query" value="" id="query" />
		    <input class="btn btn-primary" type="submit" name="submit" value="Search" />
		  </form>
		    <br/>

		<div class="panel">
			{% if result_list %}
			<div class="panel-heading">
			<h3 class="panel-title">Results</h3>
			<div class="panel-body">
			  <div class="list-group">
			  {% for result in result_list %}
			    <div class="list-group-item">
			      <h4 class="list-group-item-heading"><a href="{{result.link}}">{{ result.title }}</a></h4>

			      <button class='rango-add' class="btn btn-xs btn-default" data-catid={{category.id}} data-url={{ result.link }} data-title= {{ result.title }}>Add Page?</button>

			      <p class="list-group-item-text">{{ result.summary }}</p>
			    </div>
			  {% endfor %}
			  </div>
			</div>
			{% endif %}
			</div>
		</div>
		</div>
	</div>

	{% endif %}
{% endblock %}

templates/rango/cats.html
{% if cats %}
  <ul class="nav nav-sidebar">
  	{% for c in cats %}
  	  {% if c == act_cat %} <li class="active"> {% else %} <li> {% endif %}
  	  <a href="{% url 'category' c.slug %}">{{ c.name }}</a></li>
	{% endfor %}  	

{% else %}
  <li><strong>There are no category present.</strong></li>
  </ul>

{% endif %}

templates/rango/page_list.html
{% if pages %}
	<ul>
		{% for page in pages %}
		<li>
			<a href="{% url 'goto' %}?page_id={{page.id}}">{{ page.title }} -- you've been clicked {{page.views}} times</a></li>
		{% endfor %}

	</ul>

{% else %}
	<strong>No pages currently in category.</strong>
{% endif %}

templates/rango/profile_registration.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
<div class="col-xs-6 col-sm-6 col-sm-offset-3">
<form method="post" action="/rango/add_profile/" enctype="multipart/form-data">
  {% csrf_token %}
  <p>Your name is {{ user.username }}</p>

  {{ form.as_p }}
  <input class="btn btn-primary" type="submit" value="{% trans 'Submit' %}" />
</form>
</div>
</div>
{% endblock %}

templates/rango/register.html
{% extends 'base.html' %}
{% block body_block %}

        <h1>Register with Rango</h1>

        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'index' %}">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="{% url 'register' %}"
                enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}

{% endblock %}

templates/rango/restricted.html
{% extends 'base.html' %}

{% block content%}

	<p> hi there, {{ user.username }}!</p>
	<p> {{ info }}</p>

{% endblock %}

templates/rango/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search {% endblock %}

{% block content %}

	<div class="page-header">
		<h1>Search with Rango</h1>
		
	</div>

	<div class="row">
		<div class="panel panel-primary">
		  <br/>

		  <form class="form-inline" id="usrer-form" method="post" action="{% url 'search' %}">{% csrf_token %}
		    <input class="form-control" type="text" size="50" name="query" value="" id="query" />
		    <input class="btn btn-primary" type="submit" name="submit" value="Search" />
		  </form>
		    <br/>

		<div class="panel">
			{% if result_list %}
			<div class="panel-heading">
			<h3 class="panel-title">Results</h3>
			<div class="panel-body">
			  <div class="list-group">
			  {% for result in result_list %}
			    <div class="list-group-item">
			      <h4 class="list-group-item-heading"><a href="{{result.link}}">{{ result.title }}</a></h4>
			      <p class="list-group-item-text">{{ result.summary }}</p>
			    </div>
			  {% endfor %}
			  </div>
			</div>
			{% endif %}
			</div>
		</div>
		</div>
	</div>
{% endblock %}

templates/rango/wiki_article_detail.html
{% extends "base.html" %}
{% load markdown_deux_tags %}

{% block content %}
	{% if messages %}
	  <div class="messages">
	  	<ul>
	  		{% for message in messages  %}
	  			<li class="{{message.tag}}">{{message}}</li>
	  		{% endfor %}
	  	</ul>
	  </div>
		
	{% endif %}

	{% if not article.is_published %}
	  <label>Note: This article has not been published yet</label>
	{% endif %}

	<h2> {{ article.title }}</h2>
	<p>
		{{ article.text|markdown }}
	</p>

	<h3>Actions</h3>
	<ul>
		<li>
			<a href="{% url 'wiki_edit_article' article.slug %}">Edit?</a>
		</li>
		<li>
			<a href="{% url 'wiki_article_history' article.slug %}">View whats change</a>
		</li>
	</ul>

	<a href="{% url 'wiki_article_index' %}">See all</a>
	

{% endblock content %}

templates/rango/wiki_article_form.html
{% extends "base.html" %}
{% block content %}
	
{% if article %}
  <h1>Edit article {{ article }}</h1>

{% else %}
  <h1>Create new article</h1>

{% endif %}

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
<form action="" method="post">
	{% csrf_token %}
	<table>
        {{ form.as_p }}
        {{ edit_form.as_p }}
	</table>
	<input class="btn btn-primary" type="submit" name="submit" value="submit">
</form>
  </div>
</div>

{% endblock content %}

templates/rango/wiki_article_history.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	<div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
		<h2>History</h2>
		<h3>{{aritcle}}</h3>
		<table>
			<thead>
				<th>Edited</th>
				<th>User</th>
				<th>Summary</th>
			</thead>
			<tbody>
				{% for edit in article_history  %}
					<tr>
					    <td>{{ edit.edited_on}}</td>
					    <td>{{ edit.editor}}</td>
					    <td>{{ edit.summary}}</td>
					</tr>
				{% endfor %}
					<tr>
						<td>{{article.created_on}}</td>
						<td>{{article.author }}</td>
						<td>New article created</td>
					</tr>
			</tbody>
		</table>
		<br/>
		<a href="{% url 'wiki_article_detail' article.slug %}">Go Back</a>
	</div>
</div>



{% endblock content %}

templates/rango/wiki_index.html
{% extends "base.html" %}

{% block content %}
{% if articles %}
<h2> Recent Aritcles</h2>

<ul>
	{% for article in articles %}
	<li>
		<a href="{% url 'wiki_article_detail' article.slug %}">{{ article.title }}
	</li>
	{% endfor %}
</ul>
{% else %}
<h2>No articles have been published yet.</h2>
{% endif %}

<a href="{% url 'wiki_add_article' %}">Create new article</a>


{% endblock content %}